services:
  - type: web
    name: book-blindbox-shared
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: book-blindbox-db
          property: connectionString
      - key: PUBLIC_EDIT
        value: true
      - key: ADMIN_TOKEN
        sync: false

databases:
  - name: book-blindbox-db
    plan: free
    databaseName: book_blindbox
    user: book_blindbox
