services:
  - type: web
    name: book-blindbox-shared
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: PUBLIC_EDIT
        value: true
      - key: ADMIN_TOKEN
        sync: false
